//! The [`Toolset`] trait for grouped tools.
//!
//! A toolset is a collection of related tools defined on a single type.
//! Use the `#[toolset]` macro on an impl block to generate the implementation.
//!
//! # Example
//!
//! ```
//! use polaris_tools::{toolset, tool, ToolError};
//!
//! struct FileTools;
//!
//! #[toolset]
//! impl FileTools {
//!     #[tool]
//!     /// List files in a directory.
//!     async fn list_files(&self, path: String) -> Result<String, ToolError> {
//!         Ok("file1.txt\nfile2.txt".to_string())
//!     }
//!
//!     #[tool]
//!     /// Read a file.
//!     async fn read_file(&self, path: String) -> Result<String, ToolError> {
//!         Ok("contents".to_string())
//!     }
//! }
//! ```

use crate::tool::Tool;

/// A group of related tools.
///
/// Generated by the `#[toolset]` macro. Provides a `tools()` method that
/// returns all tools in the group for bulk registration with [`ToolRegistry`].
///
/// [`ToolRegistry`]: crate::registry::ToolRegistry
pub trait Toolset: Send + Sync + 'static {
    /// Returns all tools this toolset provides.
    fn tools(self) -> Vec<Box<dyn Tool>>;
}
